// <auto-generated />
using Lazy.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lazy.EF.Migrations
{
    [DbContext(typeof(LazyContext))]
    [Migration("20230316044737_3_EmailTemplates")]
    partial class _3_EmailTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lazy.Data.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Template 1 aaa",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Template 2 aab",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Template 3 aac",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Template 4 aad",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Template 5 aba",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Template 6 abb",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Template 7 abc",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Template 8 abd",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Template 9 aca",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Template 10 acb",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Template 11 acc",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Template 12 acd",
                            Text = "An <em>example</em> of rich text.",
                            Title = "Test email title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
