// <auto-generated />
using Lazy.DB;
using Lazy.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lazy.DB.Migrations
{
    [DbContext(typeof(LazyContext))]
    [Migration("20230202144615_1_EmailTemplates")]
    partial class _1EmailTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lazy.DB.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Html")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Html = true,
                            Name = "Template 1",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 2,
                            Html = true,
                            Name = "Template 2",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 3,
                            Html = true,
                            Name = "Template 3",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 4,
                            Html = true,
                            Name = "Template 4",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 5,
                            Html = true,
                            Name = "Template 5",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 6,
                            Html = true,
                            Name = "Template 6",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 7,
                            Html = true,
                            Name = "Template 7",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 8,
                            Html = true,
                            Name = "Template 8",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 9,
                            Html = true,
                            Name = "Template 9",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 10,
                            Html = true,
                            Name = "Template 10",
                            Text = "An <em>example</em> of rich text."
                        },
                        new
                        {
                            Id = 11,
                            Html = true,
                            Name = "Template 11",
                            Text = "An <em>example</em> of rich text."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
