// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KeySome
{
    internal sealed partial class Vsix
    {
        public const string Id = "KeySome.06b87614-b695-4f78-9278-241297d86be5";
        public const string Name = "KeySome";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Balan Stefan";
        public const string Tags = "";
    }
}
