global using ClashOfLogs.Shared;
global using Xunit;
global using DBBadgeUrls = CoL.DB.Entities.BadgeUrls;
global using DBClan = CoL.DB.Entities.Clan;
global using DBLeague = CoL.DB.Entities.League;
global using DBMember = CoL.DB.Entities.Member;
global using DBWar = CoL.DB.Entities.War;
global using DBWarClan = CoL.DB.Entities.WarClan;
// global using DBWarClanMember = CoL.DB.Entities.WarMemberOfClan;
global using DBWarMember = CoL.DB.Entities.WarMember;
// global using DBWarOpponentMember = CoL.DB.Entities.WarMemberOfOpponent;