// <auto-generated />
using System;
using CoL.DB.mssql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoL.DB.mssql.Migrations
{
    [DbContext(typeof(CoLContext))]
    [Migration("20211110185837_BaseEntity")]
    partial class BaseEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "1.0.1")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoL.DB.Entities.Clan", b =>
                {
                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClanLevel")
                        .HasColumnType("int");

                    b.Property<int>("ClanPoints")
                        .HasColumnType("int");

                    b.Property<int>("ClanVersusPoints")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsWarLogPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Members")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredTownhallLevel")
                        .HasColumnType("int");

                    b.Property<int>("RequiredTrophies")
                        .HasColumnType("int");

                    b.Property<int>("RequiredVersusTrophies")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarLosses")
                        .HasColumnType("int");

                    b.Property<int>("WarTies")
                        .HasColumnType("int");

                    b.Property<int>("WarWinStreak")
                        .HasColumnType("int");

                    b.Property<int>("WarWins")
                        .HasColumnType("int");

                    b.HasKey("Tag");

                    b.ToTable("Clans");
                });
#pragma warning restore 612, 618
        }
    }
}
